<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Monthly Payment Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #000;
            padding-bottom: 20px;
        }
        .school-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 20px;
            font-weight: bold;
            margin: 20px 0;
            text-align: center;
        }
        .report-period {
            text-align: center;
            margin-bottom: 30px;
            font-size: 16px;
        }
        .summary-box {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 30px;
            background-color: #f9f9f9;
        }
        .summary-item {
            margin-bottom: 10px;
        }
        .summary-label {
            font-weight: bold;
            display: inline-block;
            width: 200px;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            padding: 10px;
            font-size: 12px;
            border-top: 1px solid #ddd;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">SCHOOL NAME</div>
        <div>School Address Line 1</div>
        <div>School Address Line 2</div>
        <div>Phone: (123) 456-7890</div>
    </div>

    <div class="report-title">Monthly Payment Report</div>
    
    <div class="report-period">
        Period: <?= date('F Y', mktime(0, 0, 0, $month, 1, $year)) ?>
    </div>

    <div class="summary-box">
        <div class="summary-item">
            <span class="summary-label">Total Successful Payments:</span>
            <span>Rp <?= number_format($data['total_success'], 0, ',', '.') ?></span>
        </div>
        <div class="summary-item">
            <span class="summary-label">Total Pending Payments:</span>
            <span>Rp <?= number_format($data['total_pending'], 0, ',', '.') ?></span>
        </div>
        <div class="summary-item">
            <span class="summary-label">Total Failed Payments:</span>
            <span>Rp <?= number_format($data['total_failed'], 0, ',', '.') ?></span>
        </div>
        <div class="summary-item">
            <span class="summary-label">Total Students:</span>
            <span><?= $data['total_students'] ?> students</span>
        </div>
        <div class="summary-item">
            <span class="summary-label">Average Payment per Student:</span>
            <span>Rp <?= $data['total_students'] > 0 ? 
                number_format($data['total_success'] / $data['total_students'], 0, ',', '.') : 
                0 ?></span>
        </div>
    </div>

    <div style="margin-top: 50px;">
        <div style="float: right; text-align: center;">
            <p>Generated on: <?= date('d F Y H:i:s') ?></p>
            <br><br><br>
            <p>_______________________</p>
            <p>Finance Officer</p>
        </div>
    </div>

    <div class="footer">
        <div class="page-number"></div>
        Generated by SPP Payment System
    </div>
</body>
</html>
