<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Unpaid Students Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #000;
            padding-bottom: 20px;
        }
        .school-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 20px;
            font-weight: bold;
            margin: 20px 0;
            text-align: center;
        }
        .report-period {
            text-align: center;
            margin-bottom: 30px;
            font-size: 16px;
        }
        .summary-box {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 30px;
            background-color: #f9f9f9;
        }
        .summary-item {
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 12px;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .total-row {
            font-weight: bold;
            background-color: #f0f0f0;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            padding: 10px;
            font-size: 12px;
            border-top: 1px solid #ddd;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">SCHOOL NAME</div>
        <div>School Address Line 1</div>
        <div>School Address Line 2</div>
        <div>Phone: (123) 456-7890</div>
    </div>

    <div class="report-title">Unpaid Students Report</div>
    
    <div class="report-period">
        Period: <?= date('F Y', mktime(0, 0, 0, $month, 1, $year)) ?>
    </div>

    <div class="summary-box">
        <div class="summary-item">
            <strong>Total Unpaid Students:</strong> <?= count($data) ?> students
        </div>
        <div class="summary-item">
            <strong>Total Outstanding Amount:</strong> 
            Rp <?= number_format(array_sum(array_column($data, 'spp_amount')), 0, ',', '.') ?>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Student Name</th>
                <th>Class</th>
                <th>Parent Name</th>
                <th>Parent Phone</th>
                <th>SPP Amount</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $total = 0;
            foreach ($data as $index => $student): 
                $total += $student['spp_amount'];
            ?>
            <tr>
                <td><?= $index + 1 ?></td>
                <td><?= $student['name'] ?></td>
                <td><?= $student['class'] ?></td>
                <td><?= $student['parent_name'] ?></td>
                <td><?= $student['parent_phone'] ?></td>
                <td>Rp <?= number_format($student['spp_amount'], 0, ',', '.') ?></td>
            </tr>
            <?php endforeach; ?>
            <?php if (empty($data)): ?>
            <tr>
                <td colspan="6" style="text-align: center;">No unpaid students found for this period</td>
            </tr>
            <?php endif; ?>
            <tr class="total-row">
                <td colspan="5" style="text-align: right;"><strong>Total Outstanding:</strong></td>
                <td><strong>Rp <?= number_format($total, 0, ',', '.') ?></strong></td>
            </tr>
        </tbody>
    </table>

    <div style="margin-top: 50px;">
        <div style="float: right; text-align: center;">
            <p>Generated on: <?= date('d F Y H:i:s') ?></p>
            <br><br><br>
            <p>_______________________</p>
            <p>Finance Officer</p>
        </div>
    </div>

    <div class="footer">
        <div class="page-number"></div>
        Generated by SPP Payment System
    </div>
</body>
</html>
